drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),

    primary key (id)
)

CREATE TABLE member (
                        id BIGINT NOT NULL AUTO_INCREMENT,
                        name VARCHAR(255),
                        PRIMARY KEY(id)
);